In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 ={'Name':['Priyang','Aadhya','Krisha','Vedant','Parshv',
                'Mittal','Archana'],
                'Marks':[98,89,99,87,90,83,99],
                'Gender':['Male','Female','Female','Male','Male',
                         'Female','Female']
               }
df1=pd.DataFrame(dict1)
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [3]:
# 1. Display Top 3 rows of DataSet
df1.head(3)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female

In [4]:
# 2.Check last 3 rows of Dataset
df1.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [5]:
# 3. Find Shape of our Dataset (no. of rows & columns in dataset)
df1.shape

(7, 3)

In [9]:
# 4. Get Information  about our dataset like total number of rows, columns, datatypes of each columns & memory requirements
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [10]:
# 5. Check null values in the dataset
df1.isnull()

    Name  Marks  Gender
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4  False  False   False
5  False  False   False
6  False  False   False

In [11]:
# 6. Get overall Statistics about the dataframe
df1.describe()

           Marks
count   7.000000
mean   92.142857
std     6.491753
min    83.000000
25%    88.000000
50%    90.000000
75%    98.500000
max    99.000000

In [12]:
# 7.Find unique values from the Gender column
df1["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [13]:
# 8.Find the number of unique values from the gender column
df1["Gender"].nunique()

2

In [14]:
# 9. Display count of unique values in Gender column
df1["Gender"].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

In [15]:
# 10. Find total number of students having marks between 90 to 100 (inclusive) using between method
df1['Marks'].between(90,100).sum()

np.int64(4)

In [16]:
# 11. Find Average Marks
df1['Marks'].mean()

np.float64(92.14285714285714)

In [17]:
# 12. Drop the Columns
df1.drop('Gender',axis=1,inplace=True)

In [18]:
# 13. Print name of the columns
df1.columns

Index(['Name', 'Marks'], dtype='object')

In [19]:
#  14. Sort the Dataframe as per the marks column
df1.sort_values(by='Marks',ascending=False)

      Name  Marks
2   Krisha     99
6  Archana     99
0  Priyang     98
4   Parshv     90
1   Aadhya     89
3   Vedant     87
5   Mittal     83

In [36]:
df1.columns = df1.columns.str.strip().str.lower()

In [37]:
df1.columns

Index(['name', 'marks'], dtype='object')

In [43]:
## 15. Display the name & marks of female students
df1[df1['Gender'] == 'Female'][['Name', 'Marks']]

      Name  Marks
1   Aadhya     89
2   Krisha     99
5   Mittal     83
6  Archana     99